INSERT INTO Categorie (name_categorie) VALUES
('Art'),
('Mode'),
('Photographie'),
('Design'),
('Musique'),
('Cinéma'),
('Jeux vidéo'),
('Bandes dessinées'),
('Mangas'),
('Livres'),
('Cartes à collectionner'),
('Figurines'),
('Antiquités'),
('Objets vintage'),
('Montres'),
('Bijoux'),
('Sneakers'),
('NFT'),
('Peintures'),
('Sculptures'),
('Affiches'),
('Vinyles'),
('Jeux de société'),
('Maquettes'),
('Objets pop culture'),
('Technologie rétro'),
('Œuvres numériques'),
('Objets de sport'),
('Souvenirs'),
('Miniatures');