SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Categorie;
DROP TABLE IF EXISTS Contact;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS `User`;

SET FOREIGN_KEY_CHECKS = 1;
